# Generated by Django 3.0.8 on 2020-08-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Registeration',
        ),
    ]
